### ISSUE TITLE
Allow for resetting the stats database

### ISSUE THREAD

**Issue by hferentschik** [fabric8-services/fabric8-jenkins-proxy#107]
It should be possible to reset the stats database of the proxy. Either by setting an environment variable or by accessing an API endpoint. There should be the ability to purge the database as well as deleting the schema altogether.

**Comment by kishansagathiya** [comment]
@chmouel Would need more lights in terms of why this is important or `priority/major` ?

**Comment by kishansagathiya** [comment]
@chmouel @sthaha Not sure, we need this issue. The issue doesn't have any explanation regarding the same. Closing this as of now. If need be we will reopen this.
