### ISSUE TITLE
Update Jenkins build log URLs from OpenShift console pipeline view

### ISSUE THREAD

**Issue by hferentschik** [fabric8-services/fabric8-jenkins-proxy#114]
On the pipeline page w/i the OpenShift console, there are links to the Jenkins build logs. These links refer directly to the user-specific Jenkins instance/route. These links needs to point to the Jenkins Proxy URL, so that in case of an idled Jenkins instance, the service can be first scaled up again.

This issue is a placeholder to find out where code needs to change to make this happen.

**Comment by hferentschik** [comment]
@joshuawilson any update on your investigation regarding what drives the generation of this link and how we can update it?

**Comment by hferentschik** [comment]
@joshuawilson Do you have an update? Do we at least by know what drives these links?

**Comment by joshuawilson** [comment]
We are working this, hope to have it done today. If not then early tomorrow. Need to get past the CORS issue.

**Comment by hferentschik** [comment]
Ok, thanks. Keep us posted.

**Comment by joshuawilson** [comment]
waiting on the SD team to update the URLs, I have the ticket in requesting it

**Comment by hferentschik** [comment]
Mind sharing where the change needs to be done? Do you have al ink to the issue? What's the plan? Can we make this change for prod-preview first and if it looks good we will change prod once we are ready to full rollout Jenkins Proxy?

**Comment by joshuawilson** [comment]
The issue is at https://github.com/openshiftio/openshift.io/issues/1685
There are multiple PRs that change parts in the code to support it. 
This PR sets the URL https://github.com/openshiftio/saas-openshiftio/pull/598
I'm unsure if I can set that for only prod-preview and not break prod but I'm going to try.

**Comment by hferentschik** [comment]
@joshuawilson I think we are talking about different things. AFAIU fabric8-oso-proxy is needed for multi-cluster support. This is not what we are after here. We are talking about the Jenkins Proxy - fabric8-jenkins-proxy - which proxies access to the Jenkins instance in the user's workspace. In order for us to idle the Jenkins instance we need to make sure that all access (direct UI access as well as webhooks) are proxied via fabric8-jenkins-proxy. The webhook part is covered is covered in issue #94 which will update existing GitHub webhooks. 

What we try to achieve here is to make sure that the UI (the page which shows the stages of the pipeline during a build) get updated as well. The pipeline view contains a link to the Jenkins logs. This link/URL needs to change to go through the Jenkins Proxy.

**Comment by hferentschik** [comment]
@joshuawilson See https://www.awesomescreenshot.com/image/3144831/e3fa9e616b4061440bb2e61f868d1f6d

**Comment by joshuawilson** [comment]
ah, ok. thanks for the clarification. Once we are done with the multi-cluster set up in the UI we will be in a better place to help you on this.

**Comment by hferentschik** [comment]
I actually fear that this link is somehow part of the OpenShift pipeline support. Not sure how this is generated.

**Comment by hferentschik** [comment]
@vpavlin, could you please update the issue with what we discussed, regarding the jenkins-sync-plugin? Some pointers to the code we need to change as well as how we get it deployed would be nice. See https://github.com/openshift/jenkins-sync-plugin/

**Comment by hferentschik** [comment]
Ok, the related issue for this is https://github.com/fabric8io/jenkins-sync-plugin/issues/11. The jenkins-sync-plugin constructs currently the Jenkins URL in a hard coded fashion, linking to the actual Jenkins instance. This code needs to be extended to take the Jenkins URL for example via an environment variable. Or maybe there are other better ways to configure a Jenkins plugin.

**Comment by vpavlin** [comment]
One major inconsistency introduced by enabling Jenkins Proxy will be the "View log" links in OpenShift Console (Builds > Pipelines).

After looking through Console code and talking to the devs, we figured the link is taken from annotations:

html: https://github.com/openshift/origin-web-console/blob/e7a0c0a8f703d5429f70b78223abb31856a66670/app/views/directives/_build-pipeline-links.html

js: https://github.com/openshift/origin-web-console/blob/ed20b3a2eb3abfe7144644fa30a694ff04f33c6e/app/scripts/filters/resources.js#L820

The annotation is set by OpenShift sync plugin

Used here: https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/BuildSyncRunListener.java#L274

Generated here: https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java#L393

So the idea how to solve this inconsistency would be to propose a change to the sync plugin to allow using ENV var instead of OpenShift API to produce the root url.

We will also need to update Jenkins DC with the new environment variable when the sync plugin knows how to consume it

Probably here: https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/master/apps/jenkins/src/main/fabric8/openshift-deployment.yml

**Comment by hferentschik** [comment]
So really there is not really anything we need to directly do as part of this project, but let's leave this issue open in order to track it as dependency of the Proxy.

**Comment by vpavlin** [comment]
Correct, that is my understanding

One point though - we'll need all users to update their Jenkins for this to take effect

**Comment by hferentschik** [comment]
> One point though - we'll need all users to update their Jenkins for this to take effect

You mean existing users need to make sure that they get the Jenkins image with the changes discussed above? Is this something we should do via a migration as well? Updating the Jenkins image version in respective deployment config? Then there would be some work needed from us.

**Comment by vpavlin** [comment]
IIRC @aslakknutsen already did couple mass upgrades of Jenkins, so there should be a way how to do it - it does not have to happen in perfect sync with the webhook migration - things will still work for people even without new Jenkins

**Comment by hferentschik** [comment]
> IIRC already did couple mass upgrades of Jenkins, so there should be a way how to do it 

Sure. I would have expected that it is as simple as updating the used image tag

> it does not have to happen in perfect sync with the webhook migration

Understood. It's no issue until Idler gets enabled. The thing is that if it is really about making changes to some deployment configs, then we might be able to do it at the same time as the webhook migration. After all that's the point where we iterate the various namespaces anyways.

**Comment by hferentschik** [comment]
So looking at my jenkins namespace, would it not just be enough to patch (`oc patch`) the image of the jenkins deployment configuration with the new version (once it is available).

**Comment by vpavlin** [comment]
I am not sure - question is if tenant service has recorded the version somewhere? @aslakknutsen ?

**Comment by hferentschik** [comment]
> question is if tenant service has recorded the version somewhere

Why would that be? I am trying to understand where you are coming from? The other question is, where do we need to make the change that newly created users use the updated image as well? Is this what you mean?

**Comment by hferentschik** [comment]
We could also address the issue from the openshift.io UI - https://github.com/openshiftio/openshift.io/issues/2207.

**Comment by hferentschik** [comment]
So the plan for the Jenkins migration is to make it part of the migration script used for the webhook update (see issue #94). 

We should be able to use the update tenant API to trigger the Jenkins update for existing users:

    GET https://api.openshift.io/api/user
    Authorization: Bearer <generated user token>

The current migration can be found here - https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/scripts/webhook-migration/updateWebhooks.sh

For the record, the Jenkins image version used by the system is recorded here https://github.com/fabric8-services/fabric8-tenant/blob/master/JENKINS_VERSION

**Comment by hferentschik** [comment]
There are concerns that doing the migration all at once will put too much pressure on the cluster. For that reason, the migration should be split up (how!?) or run at a specific time.

@kbsingh @aslakknutsen  - what's your take on this?

**Comment by aslakknutsen** [comment]
@hferentschik I'm assuming the GH migration does not include the Jenkins migration at this point since the  cluster and URL change is rolled out. I think this can be closed?

**Comment by hferentschik** [comment]
Yupp, thanks for the heads up.
