### ISSUE TITLE
Request to Proxy timeouts before request to upstream

### ISSUE THREAD

**Issue by vpavlin** [fabric8-services/fabric8-jenkins-proxy#126]
With checks of route being available added because of #99, it sometimes happens that request to jenkins route does not finish before the request to proxy hits the timeout which then results in unexpected 504 to the loading page.

To fix this, we can use lower timeouts for the requests to Jenkins route

**Comment by hferentschik** [comment]
What determines the timeout of a HTTP request in this case? Is this browser specific? There is no way of telling when a client request times out, right?

**Comment by vpavlin** [comment]
I think it's combination of browser and OpenShift's HAProxy router, so not really.. My quick test showed we should get response from Jenkins in less than 1 s if it's up, so I'll set the timeout to 5 s, just to be sure there is enough head room

**Comment by hferentschik** [comment]
Resolved via pull request #127
