### ISSUE TITLE
Retries fail if returned status is not 200 or 202 in loading page

### ISSUE THREAD

**Issue by vpavlin** [fabric8-services/fabric8-jenkins-proxy#130]
It sometimes happens that the request to Proxy timeouts and the loading page gets 504 instead of 200 or 202. 

We need to add `default` handler so that it does not stop retrying

Addresses issue #130

**Comment by hferentschik** [comment]
Merged via pull request #130

**Comment by hferentschik** [comment]
Rebased and merged.
