### ISSUE TITLE
Proxy fails to login to Jenkins

### ISSUE THREAD

**Issue by vpavlin** [fabric8-services/fabric8-jenkins-proxy#162]
Flow that fails:
1. Restart Jenkins
2. Wait for it to start
3. Access PRoxy - get error

Flow that worked
1. Restart Jenkins
2. Wait for it to start
3. curl the login page  with OSO Token(https://jenkins-vpavlin-jenkins.1b7d.free-stg.openshiftapps.com/securityRealm/commenceLogin?from=%2F)
4. Access Proxy - get Dashboard

The presumed solution is to hit the `/securityRealm/commenceLogin` instead of just `/` to get authenticated to Jenkins via Proxy

**Comment by hferentschik** [comment]
Merged via pull request #163
