### ISSUE TITLE
Local Proxy testing is impossible due to insecure protocol

### ISSUE THREAD

**Issue by vpavlin** [fabric8-services/fabric8-jenkins-proxy#174]
When you run proxy locally with `setupLocalProxy.sh` it uses http which means cookies coming from Jenkins (which are used to verify user is logged in) will not be stored and will be thrown away by browser as they require `secure` connection (https://tools.ietf.org/html/rfc6265#section-4.1.2.5):

```
JSESSIONID.fa4b186c=node01o0uvpmvnknal1sja4z9lhvy8w323.node0; Path=/; HttpOnly; Secure
```

That means that for the local testing we need to somehow generate TLS certs and start with https - it was originally there in [testrun.go](https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/c705bb1b3b3a6b544deda9adc90e696cdfeabeea/testutils/testrun.go#L78), but it required the certs to be already present, it would be great if we could add a function to `setupLocalProxy.sh` to generate them

**Comment by hferentschik** [comment]
> That means that for the local testing we need to somehow generate TLS certs and start with https 

What exactly needs to start with HTTPS? The Proxy itself?

**Comment by vpavlin** [comment]
Yes

**Comment by kishansagathiya** [comment]
closed with https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/264
