### ISSUE TITLE
Mark phony-targets in Makefile like "all",  "clean" as ".phony"

### ISSUE THREAD

**Issue by sthaha** [fabric8-services/fabric8-jenkins-proxy#182]
We have a pretty good Makefile but I noticed that some targets need to be made `.phony` as well like the `all`, `build`, `osio` that are actually phony or doesn't result in an actual file target 
See: https://stackoverflow.com/a/2145605

**Comment by hferentschik** [comment]
The same applies to the Idler. A matching issue should be created there as well.

**Comment by kishansagathiya** [comment]
@sthaha If you are not working on this I can add a fix to this along with https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/191?

**Comment by sthaha** [comment]
@kishansagathiya sure. please do. I have set you as the assignee  now

**Comment by hferentschik** [comment]
I think we can resolve this now.
