### ISSUE TITLE
Implement memory store

### ISSUE THREAD

**Issue by chmouel** [fabric8-services/fabric8-jenkins-proxy#185]
We are currently mocking a store for tests : 

https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/0be83641eb9c8179d874708ace51486eaad92a7d/internal/storage/store_test.go#L15

It would be nice we have a proper memory storage mimicing db_store for testing and running it without db,

**Comment by kishansagathiya** [comment]
By in-memory store do you mean something simple such as have a map of Request and a map of Statistics?

**Comment by chmouel** [comment]
mostly yeah but note that it's just a nice to have and not really important to have at the moment,
