### ISSUE TITLE
Removing KeycloakURL from Configuration

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-jenkins-proxy#186]
https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/internal/proxy/proxy.go#L105
This seems to be the only place where we are using KeycloakURL.  We can get public keys from AuthURL as well. I think we can get rid of KeycloakURL from configuration if this is the only use.

**Comment by hferentschik** [comment]
https://github.com/fabric8-services/fabric8-jenkins-idler/issues/107 on the Idler side deals with getting relevant information from the Auth service. This includes using Goa to build the Auth Client. once this is merged we can use the same approach/code. 

This is not really a bug, but rather a bit of a cleanup and "doing the right thing".

**Comment by kishansagathiya** [comment]
Instead of putting the big auth client code here I would rather prefer to keep Keycloak URL. @chmouel WDYT? If we have a consensus I will close this.

**Comment by chmouel** [comment]
code copy paste generation is the way it works in Go projects, It's up to you if you want to clean this up,

**Comment by chmouel** [comment]
sounds good to me,
