### ISSUE TITLE
Remove redundant login related and token generation code

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-jenkins-proxy#189]
The fact that we require auth token as an environment variable as part of the configuration makes a lot of login related and token generation related code redundant. 

for example this file https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/internal/util/osio_token.go
https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/internal/util/jwt.go

Are we talking about different tokens here? From what I know OSIO token is Auth token.

**Comment by hferentschik** [comment]
The Auth token should indeed not be injected, it should be retrieved. This is the equivalent to https://github.com/fabric8-services/fabric8-jenkins-idler/issues/30 on the Idler side. As part of https://github.com/fabric8-services/fabric8-jenkins-idler/issues/107 I am dealing with this already. Once complete we can do something similar on the Proxy side.

Regarding osio_token.go, this is a separate command line tool. It is used for inegration testing here https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/4bc040206ac57ae888dd11b0e77ba6d05506af1a/scripts/siege/siegeJenkins.sh and it is/was used for the GitHub webhook migration here https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/2be614d503cf4d85eb7eda194fd58d85c7b7f07f/scripts/webhook-migration/updateWebhooks.sh

It is a standalone tool. I would like to see it develop to a sort of swiss army knife around various needs in osio development. Not only necessarily for Proxy. I wrote a email to the email list about it once. For now it is only used in Proxy and leaves as part of the Proxy repository. In case it grows further and more importantly, if other projects have a need for it, the plan is to create a dedicated repository. 

So there is no redundancy here atm. I suggest to close this issue and open a new one, dedicated to replace the current injetion of the Auth token with dynamic retrieval of it.

**Comment by kishansagathiya** [comment]
> I suggest to close this issue and open a new one, dedicated to replace the current injetion of the Auth token with dynamic retrieval of it.

I think @hferentschik  has implemented dynamic retrieval of auth token
