### ISSUE TITLE
Fix Proxy test TestGHData()

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-jenkins-proxy#195]
Update or delete this test https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/internal/proxy/proxy_test.go#L13-L56

**Comment by hferentschik** [comment]
I think it is safe to delete this test and then start over and create something new.

**Comment by hferentschik** [comment]
Let's go ahead and delete the test.

**Comment by hferentschik** [comment]
Merged via pull request #197
