### ISSUE TITLE
unauthorized_error on accessing jenkins.openshift.io

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-jenkins-proxy#205]
It had been around few hours since I was logged in to openshift.io
My pipelines were running all this time. It was stuck in the `approve` stage where it requires input.

Opening jenkins.openshift.io
I got 
```
{"errors":[{"code":"unauthorized_error","detail":"unknown state: oauth state reference with id '$IDENTITY' not found","status":"401","title":"Unauthorized error"}]}
```

Opened jenkins.openshift.io in another tab, right after this, it logged me in.
So this is an intermittent issue. 
This will need some investigation in terms of why is this happening. 
@sthaha Would you know anything about this? 
I have seen few other auth related issues. I think they all are related. I will find them and post.

**Comment by kishansagathiya** [comment]
This is the URL I see in the bar `https://auth.prod-preview.openshift.io/api/login?state=$STATE&code=$CODE`

**Comment by sthaha** [comment]
@sbose78 may be able to answer questions related to auth. @kishansagathiya have you tried capturing the network req/res? Please make sure you scrub any information related to tokens/auth before you paste them here

**Comment by kishansagathiya** [comment]
This one could also be because of de-provisioning of prod preview accounts, but not sure. Should wait for some days. Unless this is observed again this should be closed.

**Comment by sbose78** [comment]
Was the same `code` being used multiple times during login? Watch the network console. That should hold the key to such errors.

**Comment by kishansagathiya** [comment]
This is most likely because of de-provisioning of prod preview accounts. This hasn't been observed again.
