### ISSUE TITLE
Should we idle jenkins if pipeline is stuck at `approve` stage?

### ISSUE THREAD

**Issue by kishansagathiya** [fabric8-services/fabric8-jenkins-proxy#206]
I had pipeline waiting for my input since around 2 hours. In this scenario (https://github.com/fabric8-services/fabric8-jenkins-proxy/issues/205) it did not idle Jenkins.
Need to check if this is by design or a bug.

**Comment by kishansagathiya** [comment]
@chmouel Your comment on this one?

**Comment by chmouel** [comment]
I am not sure, what do you think @vpavlin and @kbsingh ?

**Comment by aslakknutsen** [comment]
Yes. Approve stage can stay around for months (we have examples of that), but it doesn't use a Build pod anymore. A manual promote call from UI should call the proxy then proxy start up jenkins and jenkins move on etc.. 

The promote UI call is tho currently calling Launcher, and Launcher calling OSO directly. See https://github.com/openshiftio/openshift.io/issues/2093

**Comment by kishansagathiya** [comment]
I think idler does idle if build is stuck at approve stage(which is why we had this issue https://github.com/openshiftio/openshift.io/issues/3356) I just need a confirmation from @chmouel, then we can close this.

**Comment by chmouel** [comment]
yes it should be, there is some edge case where it doesn't idle unfortunately which I never was able to track down properly (and don't seem to be the sync-plugin) but i would say that only affect us to a few jenkins at most,

**Comment by kishansagathiya** [comment]
@chmouel I would close it then. if you feel like we need this issue we can move this to the idler, anyway I have created this on the wrong repo.
