### ISSUE TITLE
Create Prometheus metrics for accessing counter

### ISSUE THREAD

**Issue by lordofthejars** [fabric8-services/fabric8-jenkins-proxy#231]
Create Prometheus metrics for how many times access to Jenkins UI are accessed and how many times of those access are coming from github webhooks.

**Comment by lordofthejars** [comment]
https://github.com/openshiftio/openshift.io/issues/2778

**Comment by kishansagathiya** [comment]
@lordofthejars 
Done with https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/232, right?
