### ISSUE TITLE
Jenkins proxy page should show message explaining capacity is full

### ISSUE THREAD

**Issue by sthaha** [fabric8-services/fabric8-jenkins-proxy#243]
Honour capacity flag and display the information if the capacity is full. 

### Usecase

User is directed to https://jenkins.openshift.io and:
- Capacity Full flag is set
   1. display that the capacity is full 
   1. keep spinning/polling until jenkins can be unidled
   1. Once jenkins can be unidled, show the unidle screen and then the Jenkins.

- Capacity Full isn't set
   - Follow the existing unidle flow - show Unidling screen if idled else Jenkins

Refer: https://github.com/openshiftio/openshift.io/issues/3320

**Comment by kishansagathiya** [comment]
@sthaha @containscafeine How about making `cluster capacity reached` an implementation detail?
In that proxy won't need to change a thing, All it needs to check is whether jenkins is up or not. Proxy wouldn't care if Jenkins is idle because the cluster has reached it's limit. WDYT?

**Comment by kishansagathiya** [comment]
I guess we will have to tell why can't we unidle jenkins https://github.com/openshiftio/openshift.io/issues/3320#issuecomment-385367093

**Comment by kishansagathiya** [comment]
Fixed with https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/248
