### ISSUE TITLE
Proxy fails to invalidate old cookies when environment is reset

### ISSUE THREAD

**Issue by sthaha** [fabric8-services/fabric8-jenkins-proxy#321]
Steps:
- log into https://jenkins.openshift.io
- reset enviroment
- access https://jenkins.openshift.io again 

Expected: 
- should ask user to relogin and then set a new jsessionid 

Actual: 
- Gets too many redirects. 

This happens because the internal cache does not reflect the fact that jenkins was reset and the old jessionid won't work anymore.

**Comment by kishansagathiya** [comment]
If we consider only `reset environment` case, we can fix this by clearing cache on reset env. On not finding cookie in cache, proxy would expire the cookie and ask for relogin.

But a more generic solution could be
- On finding a session cookie, put a check for whether the user is logged in into jenkins. Send a GET request to jenkins with the session cookie, if response is `Unauthorized` expire the cookie.

@sthaha @chmouel

**Comment by kishansagathiya** [comment]
Same situation cannot happen with jenkinsIdled cookie as we check status of Jenkins pod even if we have the cookie
