### ISSUE TITLE
ui_requests.go doesn't have unit tests

### ISSUE THREAD

**Issue by chmouel** [fabric8-services/fabric8-jenkins-proxy#336]
It is a critical part of the proxy code and we don't have unit test there.

I have added [some minimal test](https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/internal/proxy/ui_requests_test.go) for a PR sent but that's need proper unit testing.

**Comment by kishansagathiya** [comment]
resolved with https://github.com/fabric8-services/fabric8-jenkins-proxy/pull/335
