### ISSUE TITLE
Make existing unit test compile and pass

### ISSUE THREAD

**Issue by hferentschik** [fabric8-services/fabric8-jenkins-proxy#72]
At the moment most of the tests are not even compiling:

    make test
    go test -v github.com/fabric8-services/fabric8-jenkins-proxy github.com/fabric8-services/    fabric8-jenkins-proxy/api github.com/fabric8-services/fabric8-jenkins-proxy/clients github.com/    fabric8-services/fabric8-jenkins-proxy/configuration github.com/fabric8-services/    fabric8-jenkins-proxy/proxy github.com/fabric8-services/fabric8-jenkins-proxy/storage github.com/    fabric8-services/fabric8-jenkins-proxy/testutils
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy	[no test files]
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy/api	[no test files]
    # github.com/fabric8-services/fabric8-jenkins-proxy/clients_test
    clients/idler_test.go:11:35: not enough arguments in call to testutils.IdlerData1
    	have ()
    	want (string)
    clients/tenant_test.go:12:36: not enough arguments in call to testutils.TenantData1
    	have ()
    	want (string)
    FAIL	github.com/fabric8-services/fabric8-jenkins-proxy/clients [build failed]
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy/configuration	[no test files]
    # github.com/fabric8-services/fabric8-jenkins-proxy/proxy_test
    proxy/proxy_test.go:16:36: not enough arguments in call to testutils.TenantData1
    	have ()
    	want (string)
    proxy/proxy_test.go:18:35: not enough arguments in call to testutils.IdlerData1
    	have ()
    	want (string)
    proxy/proxy_test.go:25:26: not enough arguments in call to proxy.NewProxy
    	have (clients.Tenant, clients.WIT, clients.Idler, string, string, string)
    	want (clients.Tenant, clients.WIT, clients.Idler, string, string, string,     *storage.DBService, string, int)
    FAIL	github.com/fabric8-services/fabric8-jenkins-proxy/proxy [build failed]
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy/storage	[no test files]
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy/testutils	[no test files]
    make: *** [test] Error 2
    (fabric8-jenkins-proxy)
    [hardy@nineveh ~/work/developer-platform/cdk-3/go/src/github.com/fabric8-services/    fabric8-jenkins-proxy (master)]$ make test
    go test -v github.com/fabric8-services/fabric8-jenkins-proxy github.com/fabric8-services/    fabric8-jenkins-proxy/api github.com/fabric8-services/fabric8-jenkins-proxy/clients github.com/    fabric8-services/fabric8-jenkins-proxy/configuration github.com/fabric8-services/    fabric8-jenkins-proxy/proxy github.com/fabric8-services/fabric8-jenkins-proxy/storage github.com/    fabric8-services/fabric8-jenkins-proxy/testutils
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy	[no test files]
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy/api	[no test files]
    # github.com/fabric8-services/fabric8-jenkins-proxy/clients_test
    clients/idler_test.go:11:35: not enough arguments in call to testutils.IdlerData1
    	have ()
    	want (string)
    clients/tenant_test.go:12:36: not enough arguments in call to testutils.TenantData1
    	have ()
    	want (string)
    FAIL	github.com/fabric8-services/fabric8-jenkins-proxy/clients [build failed]
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy/configuration	[no test files]
    # github.com/fabric8-services/fabric8-jenkins-proxy/proxy_test
    proxy/proxy_test.go:16:36: not enough arguments in call to testutils.TenantData1
    	have ()
    	want (string)
    proxy/proxy_test.go:18:35: not enough arguments in call to testutils.IdlerData1
    	have ()
    	want (string)
    proxy/proxy_test.go:25:26: not enough arguments in call to proxy.NewProxy
    	have (clients.Tenant, clients.WIT, clients.Idler, string, string, string)
    	want (clients.Tenant, clients.WIT, clients.Idler, string, string, string,     *storage.DBService, string, int)
    FAIL	github.com/fabric8-services/fabric8-jenkins-proxy/proxy [build failed]
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy/storage	[no test files]
    ?   	github.com/fabric8-services/fabric8-jenkins-proxy/testutils	[no test files]
    make: *** [test] Error 2    

For now we should just get existing tests to compile, disabling or all deleting all tests which are obsolete. We should be able to add "make test && make fmt" to the list of targets which are getting called as part of the CI build.

**Comment by kishansagathiya** [comment]
Should we reopen this in favor of updating or deleting this test https://github.com/fabric8-services/fabric8-jenkins-proxy/blob/master/internal/proxy/proxy_test.go#L13-L56

**Comment by hferentschik** [comment]
No, never. One does not re-open an existing issue for which changes have been committed and merged. This destroys all traceability. Imagine we would cut releases and include a change for a given issue into a release and then later re-open the same issue for another release. We need to move forward. Closed issues are generally not getting re-opened. In some cases maybe (for example if you merged something and immediately notice a problem and rectify directly, but never if there is such a long time past). You want to do something about this test, create a new issue or if you just want to delete it, do it as part of whatever you do now. I should not have left the comment in there.
