### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by kbsingh** [fabric8-services/fabric8-jenkins-proxy#96]
For a user who's not been enabled, going to jenkins.openshift.io results in a 504 timeout error

**Comment by vpavlin** [comment]
Can you give us some info on the user so that we can check logs?

**Comment by hferentschik** [comment]
Also a bit more would be nice in terms of how to reproduce this.

**Comment by hferentschik** [comment]
For the record, I have seen a 504 myself once now. I don't yet know exactly how to re-produce it.

**Comment by kbsingh** [comment]
Have been unable to reproduce myself.

**Comment by hferentschik** [comment]
Ok, I am closing this then. There are quite big changes for Proxy and Idler in the pipeline. Once both are deployed we see where we are.
